import { StyleSheet } from 'react-native';
import { Color, Border, FontSize, FontFamily } from "../../GlobalStyles";

export default StyleSheet.create({
  profileLayout: {
    width: 390,
    backgroundColor: Color.colorAliceblue,
    borderRadius: Border.br_13xl,
    left: 0,
    position: "absolute",
  },
  edit2Position: {
    left: 298,
    overflow: "hidden",
  },
  e11Typo: {
    textAlign: "center",
    color: Color.colorDarkslategray,
    lineHeight: 17,
    fontSize: FontSize.size_sm,
  },
  fullNameTypo: {
    top: 76,
    opacity: 0.7,
    lineHeight: 14,
    fontSize: FontSize.size_xs,
    textAlign: "center",
    color: Color.colorDarkslategray,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    position: "absolute",
  },
  groupItemPosition: {
    left: "50%",
    position: "absolute",
  },
  sunIconPosition: {
    top: 6,
    position: "absolute",
  },
  parentLayout: {
    height: 44,
    top: 0,
  },
  homeTypo: {
    top: 30,
    lineHeight: 14,
    fontSize: FontSize.size_xs,
    textAlign: "center",
    color: Color.colorDarkslategray,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
  },
  iconPosition: {
    height: 26,
    top: 0,
    position: "absolute",
  },
  homePosition: {
    width: 31,
    left: 0,
    position: "absolute",
  },
  profileChildLayout: {
    left: 15,
    height: 28,
    borderWidth: 2,
    borderColor: Color.colorAliceblue,
    borderStyle: "solid",
    width: 358,
    borderRadius: Border.br_13xl,
    position: "absolute",
  },
  chevronIconLayout: {
    height: 24,
    width: 24,
    left: 334,
    position: "absolute",
    overflow: "hidden",
  },
  profileChild: {
    top: -18,
    height: 255,
  },
  profileItem: {
    top: 741,
    height: 122,
  },
  edit2: {
    top: 59,
    width: 9,
    height: 9,
    position: "absolute",
  },
  vectorIcon: {
    height: "0.88%",
    width: "1.9%",
    top: "9.36%",
    right: "24%",
    bottom: "89.76%",
    left: "74.1%",
    maxWidth: "100%",
    maxHeight: "100%",
    position: "absolute",
    overflow: "hidden",
  },
  danaYaakovArye: {
    top: 89,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    color: Color.colorDarkslategray,
    lineHeight: 17,
    fontSize: FontSize.size_sm,
    left: 32,
    position: "absolute",
  },
  e11: {
    top: 130,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    color: Color.colorDarkslategray,
    lineHeight: 17,
    fontSize: FontSize.size_sm,
    left: 32,
    position: "absolute",
  },
  userName: {
    top: 116,
    opacity: 0.7,
    lineHeight: 14,
    fontSize: FontSize.size_xs,
    textAlign: "center",
    color: Color.colorDarkslategray,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    left: 32,
    position: "absolute",
  },
  fullName: {
    left: 32,
  },
  editDetails: {
    left: 300,
  },
  profileInner: {
    marginLeft: -74,
    top: 133,
    width: 148,
    height: 148,
  },
  groupChild: {
    top: 0,
    height: 29,
    width: 358,
    marginLeft: -179,
    left: "50%",
    backgroundColor: Color.colorAliceblue,
    borderRadius: Border.br_13xl,
    position: "absolute",
  },
  hiSisEvery: {
    left: 41,
    letterSpacing: -0.1,
    fontFamily: FontFamily.gloryRegular,
    width: 241,
    height: 18,
    textAlign: "center",
    color: Color.colorDarkslategray,
    lineHeight: 17,
    fontSize: FontSize.size_sm,
  },
  sunIcon: {
    width: 18,
    height: 19,
    left: 298,
    overflow: "hidden",
  },
  rectangleParent: {
    top: 297,
    height: 29,
    width: 358,
    marginLeft: -179,
    left: "50%",
    position: "absolute",
  },
  groupIcon: {
    top: 261,
    left: 227,
    width: 17,
    height: 17,
    position: "absolute",
  },
  insight: {
    width: 42,
    position: "absolute",
    left: 0,
  },
  icon: {
    left: 8,
    width: 27,
  },
  insightParent: {
    left: 103,
    width: 42,
    position: "absolute",
  },
  settingsParent: {
    left: 217,
    width: 42,
    position: "absolute",
  },
  home: {
    top: 30,
    lineHeight: 14,
    fontSize: FontSize.size_xs,
    textAlign: "center",
    color: Color.colorDarkslategray,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
  },
  icon2: {
    left: 3,
    width: 26,
  },
  homeParent: {
    height: 44,
    top: 0,
  },
  groupItem: {
    marginLeft: 100.5,
    top: 46,
    borderRadius: Border.br_17xl,
    width: 16,
    height: 1,
  },
  groupParent: {
    top: 755,
    left: 65,
    width: 259,
    height: 47,
    position: "absolute",
  },
  rectangleView: {
    top: 342,
    left: 16,
    height: 28,
    borderWidth: 2,
    borderColor: Color.colorAliceblue,
    borderStyle: "solid",
    width: 358,
    borderRadius: Border.br_13xl,
    position: "absolute",
  },
  profileChild1: {
    top: 386,
  },
  profileChild2: {
    top: 474,
  },
  profileChild3: {
    top: 430,
  },
  chevronDownIcon: {
    top: 344,
  },
  termsAndConditions: {
    top: 347,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    left: 32,
    position: "absolute",
  },
  chevronDownIcon1: {
    top: 388,
  },
  confidentiality: {
    top: 391,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    left: 32,
    position: "absolute",
  },
  changeTheOrder: {
    top: 435,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    left: 32,
    position: "absolute",
  },
  chevronDownIcon2: {
    top: 432,
  },
  chevronDownIcon3: {
    top: 476,
  },
  submitASymptom: {
    top: 479,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    left: 32,
    position: "absolute",
  },
  profileChild4: {
    top: 519,
  },
  chevronDownIcon4: {
    top: 521,
  },
  contactSupport: {
    top: 524,
    fontFamily: FontFamily.fbSpoilerPasEng,
    fontWeight: "300",
    left: 32,
    position: "absolute",
  },
  profile: {
    borderRadius: Border.br_26xl,
    backgroundColor: Color.colorGray_100,
    flex: 1,
    width: "100%",
    height: 844,
    overflow: "hidden",
  },
});